# Generated by Django 5.1.4 on 2024-12-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelArtic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=150)),
                ('priceMa', models.FloatField()),
                ('priceMi', models.FloatField()),
                ('row', models.IntegerField(default=0)),
                ('col', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('priceXlsx', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='core_modela_code_5d85b3_idx')],
            },
        ),
    ]
