# Generated by Django 5.1.4 on 2024-12-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_modelartic_col_remove_modelartic_pricexlsx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelArticOnePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=150)),
                ('price', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='core_modela_code_ec49a9_idx')],
            },
        ),
    ]
