# Generated by Django 5.1.4 on 2024-12-09 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_modelarticoneprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelImgArtic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField()),
                ('artic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.modelartic', verbose_name='Article')),
            ],
        ),
    ]
