# Generated by Django 5.1.4 on 2024-12-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_modelartic_imgs_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelartic',
            name='imgs_path',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
