# Generated by Django 5.1.4 on 2024-12-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_modelartic_imgs_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='modelartic',
            name='imgs_path',
            field=models.FilePathField(blank=True, null=True, path=None),
        ),
        migrations.AddField(
            model_name='modelartic',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='core.tag'),
        ),
    ]
