# Generated by Django 5.1.4 on 2024-12-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tag_alter_modelartic_imgs_path_modelartic_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AlterField(
            model_name='modelartic',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='core.modeltag'),
        ),
    ]
