# Generated by Django 5.1.4 on 2024-12-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_modeltag_delete_tag_alter_modelartic_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelarticoneprice',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='category', to='core.modeltag'),
        ),
    ]
