# Generated by Django 5.1.4 on 2025-07-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_modelarticoneprice_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelarticoneprice',
            name='tags',
        ),
        migrations.CreateModel(
            name='ModelClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuil', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=36)),
                ('empress_name', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=24)),
                ('email', models.CharField(max_length=64)),
                ('lists_tags', models.ManyToManyField(blank=True, related_name='lists', to='core.modeltag')),
            ],
        ),
        migrations.AddField(
            model_name='modelarticoneprice',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
