# Generated by Django 5.1.4 on 2025-07-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_modelarticoneprice_tags_modelclient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelclient',
            name='cuil',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
