# Generated by Django 5.1.4 on 2025-07-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_modelclient_cuil'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenCreateClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
            ],
        ),
    ]
