# Generated by Django 5.1.4 on 2025-07-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_tokencreateclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelclient',
            name='list_number',
            field=models.IntegerField(choices=[(1, 'Minorista'), (5, 'Mayorista')], default=5),
            preserve_default=False,
        ),
    ]
