# Generated by Django 5.1.4 on 2025-07-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_modelclient_list_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelclient',
            name='list_number',
            field=models.CharField(choices=[('1', 'Minorista'), ('5', 'Mayorista')], max_length=1),
        ),
    ]
