# Generated by Django 5.1.4 on 2025-07-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_modelclient_list_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelclient',
            name='bussines',
            field=models.CharField(choices=[('Buloneria', 'Buloneria'), ('Ferreteria', 'Ferreteria'), ('Distribuidor', 'Distribuidor')], default='Buloneria', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelclient',
            name='message',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
