# Generated by Django 5.1.4 on 2025-07-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_modelclient_bussines_modelclient_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelclient',
            name='bussines',
            field=models.CharField(choices=[('Distribuidor', 'Distribuidor'), ('Mayorista', 'Mayorista'), ('Buloneria', 'Buloneria'), ('Ferreteria', 'Ferreteria'), ('Revendedor', 'Revendedor')], max_length=16),
        ),
    ]
