# Generated by Django 5.1.4 on 2024-12-05 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelartic',
            name='col',
        ),
        migrations.RemoveField(
            model_name='modelartic',
            name='priceXlsx',
        ),
        migrations.RemoveField(
            model_name='modelartic',
            name='row',
        ),
    ]
