# Generated by Django 5.1.4 on 2024-12-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_modelimgartic'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelartic',
            name='imgs_path',
            field=models.FilePathField(null=True),
        ),
    ]
